name: CI (Build Java Project & Push DockerHub)
on:
  push:
    branches: 'main'
    tags: 'v*'

env:
    DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.PROJECT_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Move Java code
      run: |
        mv build_sample/app/* ./
    - name: Setup Java Build Environment
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.3'
    - name: Build with Gradle
      run: ./gradlew build
    # # 도커 메타
    # - name: Docker meta
    #   id: docker_meta
    #   uses: crazy-max/ghaction-docker-meta@v1
    #   with:
    #     images: ${{ env.DOCKER_IMAGE_NAME }}
    #     tag-semver: |
    #       {{version}}
    #       {{major}}.{{minor}}
    # # 도커 빌드 관련 셋업
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # 도커 허브 로그인
    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    # 도커이미지 빌드하고 허브에 업로드
    - name: Container Build and Push to DockerHub
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ github.sha }}
          #tags: ${{ steps.docker_meta.outputs.tags }}
          #labels: ${{ steps.docker_meta.outputs.labels }}
    # - name: Get Tag Name
    #   id: get-tag-name
    #   run: echo "TAG_NAME=${{steps.docker_meta.outputs.labels}}" >> $GITHUB_OUTPUT
  # EC2에 배포
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_SSH_ID }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
          sudo docker rm -f ${{ vars.PROJECT_NAME }}
          sudo docker rmi $(docker images |grep ${{ env.DOCKER_IMAGE_NAME }} |awk '{print $3}')
          sudo docker run --name ${{ vars.PROJECT_NAME }} -d -p 80:8080 ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}